dist: trusty
sudo: false
language: java
addons:
    apt:
        packages:
            - protobuf-compiler

env:
    global:
        - GRADLE_VERSION='3.5-20170305000422+0000'
        - GRADLE_DISTRIBUTION_URL="https://repo.gradle.org/gradle/dist-snapshots/gradle-script-kotlin-$GRADLE_VERSION-bin.zip"
        - TERM=dumb
jdk:
    - oraclejdk8
    - openjdk8
before_install:
    - (
           cd "${HOME}"
        && curl -sSLO "${GRADLE_DISTRIBUTION_URL}"
        && unzip -q $(basename "${GRADLE_DISTRIBUTION_URL}")
        && mv "gradle-${GRADLE_VERSION}" "gradle"
      )
    - export PATH="${HOME}/gradle/bin:${PATH}"
    - hash -r
    - gradle --version
script:
    - gradle build

notifications:
    email: false
