dist: trusty
sudo: false
language: generic
addons:
    apt:
        packages:
            - protobuf-compiler
env:
    - PROTOC_OUT=cpp
script:
    - mkdir -p "build/${PROTOC_OUT}"
    - protoc "--${PROTOC_OUT}_out=build/${PROTOC_OUT}" src/*.proto
