dist: trusty
sudo: false
language: java
addons:
    apt:
        packages:
            - protobuf-compiler

env:
    global:
        - GRADLE_VERSION='4.4'
        - GRADLE_DISTRIBUTION_URL="https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip"
        - TERM=dumb
jdk:
    - oraclejdk8
    - oraclejdk9
    - openjdk8
matrix:
    allow_failures:
        - jdk: oraclejdk9
before_install:
    - (
           cd "${HOME}"
        && curl -sSLO "${GRADLE_DISTRIBUTION_URL}"
        && unzip -q $(basename "${GRADLE_DISTRIBUTION_URL}")
        && mv "gradle-${GRADLE_VERSION}" "gradle"
      )
    - export PATH="${HOME}/gradle/bin:${PATH}"
    - hash -r
    - gradle --version
    - protoc --version
script:
    - gradle build

notifications:
    email: false
